module.exports = {
  0: "Wszystkie branże",
  1: "Architektura, budownictwo",
  2: "Biotechnologia",
  3: "Chemia",
  4: "Doradztwo, consulting",
  5: "Edukacja, szkolenia",
  6: "Ekologia, energie odnawialne",
  7: "Elektronika, elektrotechnika",
  8: "Finanse, ubezpieczenia",
  9: "Gastronomia",
  10: "Handel hurtowy i detaliczny",
  11: "Informatyka, IT, internet",
  12: "Marketing, reklama",
  13: "Media",
  14: "Medycyna, farmacja",
  15: "Motoryzacja",
  16: "Nieruchomości",
  17: "Ochrona środowiska",
  18: "Paliwa, energia, gaz",
  19: "Produkcja - inne",
  20: "Rolnictwo",
  21: "Rozrywka, kultura, sport",
  22: "Sprzęt, maszyny, urządzenia",
  23: "Transport, spedycja, logistyka",
  24: "Turystyka, hotele",
  25: "Usługi - inne",
  26: "Inna branża"
};
